package com.name.crow.dao.domain.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.name.crow.dao.domain.Role;
import com.name.crow.dao.domain.User;

/**
 * Class _UserRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserRole extends CayenneDataObject {

    public static final String CREATED_DATE_PROPERTY = "createdDate";
    public static final String ROLE_ID_PROPERTY = "roleId";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String ROLEID_PROPERTY = "roleid";
    public static final String USERID_PROPERTY = "userid";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedDate(Date createdDate) {
        writeProperty(CREATED_DATE_PROPERTY, createdDate);
    }
    public Date getCreatedDate() {
        return (Date)readProperty(CREATED_DATE_PROPERTY);
    }

    public void setRoleId(Integer roleId) {
        writeProperty(ROLE_ID_PROPERTY, roleId);
    }
    public Integer getRoleId() {
        return (Integer)readProperty(ROLE_ID_PROPERTY);
    }

    public void setUserId(Integer userId) {
        writeProperty(USER_ID_PROPERTY, userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty(USER_ID_PROPERTY);
    }

    public void addToRoleid(Role obj) {
        addToManyTarget(ROLEID_PROPERTY, obj, true);
    }
    public void removeFromRoleid(Role obj) {
        removeToManyTarget(ROLEID_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Role> getRoleid() {
        return (List<Role>)readProperty(ROLEID_PROPERTY);
    }


    public void addToUserid(User obj) {
        addToManyTarget(USERID_PROPERTY, obj, true);
    }
    public void removeFromUserid(User obj) {
        removeToManyTarget(USERID_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<User> getUserid() {
        return (List<User>)readProperty(USERID_PROPERTY);
    }


}
