package com.name.crow.dao.auto;

import org.apache.cayenne.CayenneDataObject;

import java.util.Date;

/**
 * Class _Role was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Role extends CayenneDataObject {

    public static final String CREATED_DATE_PROPERTY = "createdDate";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ROLENAME_PROPERTY = "rolename";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedDate(Date createdDate) {
        writeProperty(CREATED_DATE_PROPERTY, createdDate);
    }
    public Date getCreatedDate() {
        return (Date)readProperty(CREATED_DATE_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setRolename(String rolename) {
        writeProperty(ROLENAME_PROPERTY, rolename);
    }

    public String getRolename() {
        return (String) readProperty(ROLENAME_PROPERTY);
    }

}
