package com.name.crow.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Scm was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Scm extends CayenneDataObject {

    public static final String CREATED_DATE_PROPERTY = "createdDate";
    public static final String ENDPOINT_PROPERTY = "endpoint";
    public static final String MODIFIED_DATE_PROPERTY = "modifiedDate";
    public static final String NAME_PROPERTY = "name";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedDate(Date createdDate) {
        writeProperty(CREATED_DATE_PROPERTY, createdDate);
    }

    public Date getCreatedDate() {
        return (Date) readProperty(CREATED_DATE_PROPERTY);
    }

    public void setEndpoint(String endpoint) {
        writeProperty(ENDPOINT_PROPERTY, endpoint);
    }

    public String getEndpoint() {
        return (String) readProperty(ENDPOINT_PROPERTY);
    }

    public void setModifiedDate(Date modifiedDate) {
        writeProperty(MODIFIED_DATE_PROPERTY, modifiedDate);
    }

    public Date getModifiedDate() {
        return (Date) readProperty(MODIFIED_DATE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }

    public String getName() {
        return (String) readProperty(NAME_PROPERTY);
    }

}
