package com.name.crow.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _UserAccount was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserAccount extends CayenneDataObject {

    public static final String CREATED_DATE_PROPERTY = "createdDate";
    public static final String EMAIL_PROPERTY = "email";
    public static final String IS_ADMIN_PROPERTY = "isAdmin";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String USERNAME_PROPERTY = "username";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedDate(Date createdDate) {
        writeProperty(CREATED_DATE_PROPERTY, createdDate);
    }

    public Date getCreatedDate() {
        return (Date) readProperty(CREATED_DATE_PROPERTY);
    }

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }

    public String getEmail() {
        return (String) readProperty(EMAIL_PROPERTY);
    }

    public void setIsAdmin(Boolean isAdmin) {
        writeProperty(IS_ADMIN_PROPERTY, isAdmin);
    }

    public Boolean getIsAdmin() {
        return (Boolean) readProperty(IS_ADMIN_PROPERTY);
    }

    public void setPassword(String password) {
        writeProperty(PASSWORD_PROPERTY, password);
    }

    public String getPassword() {
        return (String) readProperty(PASSWORD_PROPERTY);
    }

    public void setUsername(String username) {
        writeProperty(USERNAME_PROPERTY, username);
    }

    public String getUsername() {
        return (String) readProperty(USERNAME_PROPERTY);
    }

}
