package com.name.crow.dao.auto;

import com.name.crow.dao.Role;
import com.name.crow.dao.UserAccount;
import org.apache.cayenne.CayenneDataObject;

import java.util.Date;

/**
 * Class _UserRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserRole extends CayenneDataObject {

    public static final String CREATED_DATE_PROPERTY = "createdDate";
    public static final String ROLEID_PROPERTY = "roleid";
    public static final String USERID_PROPERTY = "userid";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedDate(Date createdDate) {
        writeProperty(CREATED_DATE_PROPERTY, createdDate);
    }
    public Date getCreatedDate() {
        return (Date)readProperty(CREATED_DATE_PROPERTY);
    }

    public void setRoleid(Role roleid) {
        setToOneTarget(ROLEID_PROPERTY, roleid, true);
    }

    public Role getRoleid() {
        return (Role) readProperty(ROLEID_PROPERTY);
    }


    public void setUserid(UserAccount userid) {
        setToOneTarget(USERID_PROPERTY, userid, true);
    }

    public UserAccount getUserid() {
        return (UserAccount) readProperty(USERID_PROPERTY);
    }


}
