package com.name.crow.dao.auto;

import java.util.List;

import com.name.crow.dao.ScmStatus;
import com.name.crow.dao.WorkflowStatus;
import org.apache.cayenne.CayenneDataObject;

/**
 * Class _WorkflowScmStatusMapping was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WorkflowScmStatusMapping extends CayenneDataObject {

    public static final String SCM_STATUS_ID_STATUS_ID_PROPERTY = "scmStatusIdStatusId";
    public static final String WORKFLPW_STATUS_WORKFLOW_STATUS_PROPERTY = "workflpwStatusWorkflowStatus";

    public static final String ID_PK_COLUMN = "id";

    public void addToScmStatusIdStatusId(ScmStatus obj) {
        addToManyTarget(SCM_STATUS_ID_STATUS_ID_PROPERTY, obj, true);
    }
    public void removeFromScmStatusIdStatusId(ScmStatus obj) {
        removeToManyTarget(SCM_STATUS_ID_STATUS_ID_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ScmStatus> getScmStatusIdStatusId() {
        return (List<ScmStatus>)readProperty(SCM_STATUS_ID_STATUS_ID_PROPERTY);
    }


    public void addToWorkflpwStatusWorkflowStatus(WorkflowStatus obj) {
        addToManyTarget(WORKFLPW_STATUS_WORKFLOW_STATUS_PROPERTY, obj, true);
    }
    public void removeFromWorkflpwStatusWorkflowStatus(WorkflowStatus obj) {
        removeToManyTarget(WORKFLPW_STATUS_WORKFLOW_STATUS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WorkflowStatus> getWorkflpwStatusWorkflowStatus() {
        return (List<WorkflowStatus>)readProperty(WORKFLPW_STATUS_WORKFLOW_STATUS_PROPERTY);
    }


}
