package com.name.crow.dao.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _WorkflowStatus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WorkflowStatus extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String STATUS_VALUE_PROPERTY = "statusValue";

    public static final String ID_PK_COLUMN = "id";

    public void setId(Long id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Long getId() {
        return (Long)readProperty(ID_PROPERTY);
    }

    public void setStatusValue(String statusValue) {
        writeProperty(STATUS_VALUE_PROPERTY, statusValue);
    }
    public String getStatusValue() {
        return (String)readProperty(STATUS_VALUE_PROPERTY);
    }

}
